# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialog_dataUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setEnabled(True)
        Dialog.resize(433, 366)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/resources/auto_logo.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        Dialog.setStyleSheet("background-color:rgb(200,230,255);   ")
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setStyleSheet("QGroupBox{\n"
"                  padding-right: 15px;\n"
"                   border-style:inset;                  \n"
"                   border-width:1px;                    \n"
"                   border-radius:1px;                   \n"
"                   border-color:rgb(255,255,255);   \n"
"                   font: 15px;                       \n"
"                   color:rgb(2,2,2);                \n"
"                   padding:6px; \n"
"}\n"
"QLabel{\n"
"font:15px;                       \n"
"color:rgb(2,2,2);                \n"
"}\n"
"\n"
"QSpinBox{\n"
"padding-right: 15px; /* make room for the arrows */\n"
"border:1px solid rgba(255,255,255,200);\n"
"border-radius:5px;       \n"
"  \n"
"background-color: rgba(255, 255, 255,10);\n"
"font:18px;      \n"
"color:rgb(2,2,2);\n"
"} \n"
"\n"
"QSpinBox::up-button {\n"
"border-image: url(:/images/resources/spinbox-up.png);\n"
"}\n"
"\n"
"QSpinBox::down-button {\n"
"border-image: url(:/images/resources/spinbox-down.png);\n"
"}\n"
"\n"
"QSpinBox::up-button:pressed {\n"
"margin-top:3px;\n"
"}\n"
"\n"
"QSpinBox::down-button:pressed {\n"
"margin-bottom:3px;\n"
"}")
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 0, 3, 1, 1)
        self.sb_year = QtWidgets.QSpinBox(self.groupBox)
        self.sb_year.setProperty("showGroupSeparator", False)
        self.sb_year.setMinimum(2004)
        self.sb_year.setMaximum(2008)
        self.sb_year.setObjectName("sb_year")
        self.gridLayout_2.addWidget(self.sb_year, 0, 2, 1, 1)
        self.sb_zone = QtWidgets.QSpinBox(self.groupBox)
        self.sb_zone.setWrapping(False)
        self.sb_zone.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.sb_zone.setMinimum(0)
        self.sb_zone.setMaximum(20)
        self.sb_zone.setObjectName("sb_zone")
        self.gridLayout_2.addWidget(self.sb_zone, 0, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 0, 7, 1, 1)
        self.sb_day = QtWidgets.QSpinBox(self.groupBox)
        self.sb_day.setMinimum(0)
        self.sb_day.setMaximum(31)
        self.sb_day.setObjectName("sb_day")
        self.gridLayout_2.addWidget(self.sb_day, 0, 6, 1, 1)
        self.sb_month = QtWidgets.QSpinBox(self.groupBox)
        self.sb_month.setMinimum(0)
        self.sb_month.setMaximum(12)
        self.sb_month.setObjectName("sb_month")
        self.gridLayout_2.addWidget(self.sb_month, 0, 4, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 0, 5, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 1, 1, 1)
        self.gridLayout_2.setColumnStretch(0, 1)
        self.gridLayout_2.setColumnStretch(2, 1)
        self.gridLayout_2.setColumnStretch(4, 1)
        self.gridLayout_2.setColumnStretch(6, 1)
        self.gridLayout.addWidget(self.groupBox, 1, 0, 1, 3)
        self.btn_yes = QtWidgets.QPushButton(Dialog)
        self.btn_yes.setStyleSheet("\n"
"QPushButton{\n"
"                  padding-right: 15px;\n"
"                   border-style:inset;                  \n"
"                   border-width:1px;                    \n"
"                   border-radius:1px;                   \n"
"                   border-color:rgb(255,255,255);   \n"
"                   font: 15px;                       \n"
"                   color:rgb(2,2,2);                \n"
"                   padding:6px; \n"
"\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"                   background-color:rgba(100,150,180,200);\n"
"                   border-color:rgba(255,255,255,30);\n"
"                   border-style:inset;\n"
"                   color:rgba(0,0,0,100);\n"
"font:bold 15px;\n"
"}\n"
"\n"
" QPushButton:hover{\n"
"                   background-color:rgb(200,225,255);\n"
"                   border-color:rgba(255,255,255,200);\n"
"                   color:rgba(0,0,0,200);\n"
"font:bold 15px;\n"
"                   }")
        self.btn_yes.setObjectName("btn_yes")
        self.gridLayout.addWidget(self.btn_yes, 3, 1, 1, 1)
        self.btn_no = QtWidgets.QPushButton(Dialog)
        self.btn_no.setStyleSheet("\n"
"\n"
"QPushButton{\n"
"                  padding-right: 15px;\n"
"                   border-style:inset;                  \n"
"                   border-width:1px;                    \n"
"                   border-radius:1px;                   \n"
"                   border-color:rgb(255,255,255);   \n"
"                   font: 15px;                       \n"
"                   color:rgb(2,2,2);                \n"
"                   padding:6px; \n"
"\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"                   background-color:rgba(100,150,180,200);\n"
"                   border-color:rgba(255,255,255,30);\n"
"                   border-style:inset;\n"
"                   color:rgba(0,0,0,100);\n"
"font:bold 15px;\n"
"}\n"
"\n"
" QPushButton:hover{\n"
"                   background-color:rgb(200,225,255);\n"
"                   border-color:rgba(255,255,255,200);\n"
"                   color:rgba(0,0,0,200);\n"
"font:bold 15px;\n"
"                   }")
        self.btn_no.setObjectName("btn_no")
        self.gridLayout.addWidget(self.btn_no, 3, 2, 1, 1)
        self.listWidget = QtWidgets.QListWidget(Dialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.listWidget.setFont(font)
        self.listWidget.setStyleSheet("background-color: rgb(255, 255, 255); \n"
"padding-right: 15px;\n"
"                   border-style:inset;                  \n"
"                   border-width:1px;                    \n"
"                   border-radius:15px;  ")
        self.listWidget.setObjectName("listWidget")
        self.gridLayout.addWidget(self.listWidget, 0, 0, 1, 3)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 3, 0, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_2.setStyleSheet("QGroupBox{\n"
"                  padding-right: 15px;\n"
"                   border-style:inset;                  \n"
"                   border-width:1px;                    \n"
"                   border-radius:1px;                   \n"
"                   border-color:rgb(255,255,255);   \n"
"                   font: 15px;                       \n"
"                   color:rgb(2,2,2);                \n"
"                   padding:6px; \n"
"}\n"
"\n"
"QPushButton{\n"
" image-position: left;\n"
"\n"
"                  padding-right: 15px;\n"
"                   border-style:inset;                  \n"
"                   border-width:2px;                    \n"
"                   border-radius:1px;                   \n"
"                   border-color:rgba(255,255,255,100);   \n"
"                   font:18px;                       \n"
"                   color:rgb(2,2,2);                \n"
"                   padding:6px; \n"
"\n"
"}\n"
" QPushButton:hover{\n"
"                   background-color:rgb(200,225,255);\n"
"                   border-color:rgba(255,255,255,200);\n"
"                   color:rgba(0,0,0,200);\n"
"font:bold 20px;\n"
"                   }")
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.btn_add = QtWidgets.QPushButton(self.groupBox_2)
        self.btn_add.setObjectName("btn_add")
        self.gridLayout_3.addWidget(self.btn_add, 0, 0, 1, 1)
        self.btn_cle = QtWidgets.QPushButton(self.groupBox_2)
        self.btn_cle.setObjectName("btn_cle")
        self.gridLayout_3.addWidget(self.btn_cle, 0, 2, 1, 1)
        self.btn_del = QtWidgets.QPushButton(self.groupBox_2)
        self.btn_del.setObjectName("btn_del")
        self.gridLayout_3.addWidget(self.btn_del, 0, 1, 1, 1)
        self.gridLayout.addWidget(self.groupBox_2, 2, 0, 1, 3)
        self.gridLayout.setColumnStretch(0, 2)
        self.gridLayout.setRowStretch(0, 2)
        self.gridLayout.setRowStretch(1, 1)
        self.gridLayout.setRowStretch(2, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "负荷数据选择"))
        self.groupBox.setTitle(_translate("Dialog", "负荷数据选择"))
        self.label_2.setText(_translate("Dialog", "年"))
        self.label_4.setText(_translate("Dialog", "日"))
        self.label_3.setText(_translate("Dialog", "月"))
        self.label.setText(_translate("Dialog", "地区"))
        self.btn_yes.setText(_translate("Dialog", "确认"))
        self.btn_no.setText(_translate("Dialog", "取消"))
        self.groupBox_2.setTitle(_translate("Dialog", "功能选择"))
        self.btn_add.setText(_translate("Dialog", "添加"))
        self.btn_cle.setText(_translate("Dialog", "清除"))
        self.btn_del.setText(_translate("Dialog", "删除"))
import res_rc
