# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindowUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Mainwindow(object):
    def setupUi(self, Mainwindow):
        Mainwindow.setObjectName("Mainwindow")
        Mainwindow.setEnabled(True)
        Mainwindow.resize(1280, 900)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/resources/auto_logo.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Mainwindow.setWindowIcon(icon)
        Mainwindow.setWindowOpacity(1.0)
        Mainwindow.setStyleSheet("")
        Mainwindow.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        Mainwindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(Mainwindow)
        self.centralwidget.setEnabled(True)
        self.centralwidget.setStyleSheet("#centralwidget{\n"
" border-image: url(:/images/resources/bj.png);\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setStyleSheet("")
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.btn_1check = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_1check.sizePolicy().hasHeightForWidth())
        self.btn_1check.setSizePolicy(sizePolicy)
        self.btn_1check.setStyleSheet("QPushButton{\n"
" image-position: left;                   \n"
"    padding-right: 15px;    \n"
"    image: url(:/images/resources/数据查看.svg);\n"
"background-color: rgba(18, 107, 214,100);\n"
"  \n"
"                   font:bold 18px;                       \n"
"                   color:rgba(255,255,255,100);                \n"
"                   padding:20px; \n"
"\n"
"}\n"
"\n"
"\n"
"\n"
" QPushButton:hover{\n"
"                   background-color:rgb(200,225,255);\n"
"                   border-color:rgba(255,255,255,200);\n"
"                   color:rgba(0,0,0,200);\n"
"                font:bold 24px;\n"
"                   }")
        self.btn_1check.setObjectName("btn_1check")
        self.verticalLayout.addWidget(self.btn_1check)
        self.btn_2show = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_2show.sizePolicy().hasHeightForWidth())
        self.btn_2show.setSizePolicy(sizePolicy)
        self.btn_2show.setStyleSheet("QPushButton{\n"
" image-position: left;\n"
"                       padding-right: 15px;\n"
"    image: url(:/images/resources/负荷监控.svg);\n"
"\n"
"background-color: rgba(18, 107, 214,100);\n"
"  \n"
"                   font:bold 18px;                       \n"
"                   color:rgba(255,255,255,100);                \n"
"                   padding:20px; \n"
"\n"
"}\n"
"\n"
"\n"
"\n"
" QPushButton:hover{\n"
"                   background-color:rgb(200,225,255);\n"
"                   border-color:rgba(255,255,255,200);\n"
"                   color:rgba(0,0,0,200);\n"
"                font:bold 24px;\n"
"                   }")
        self.btn_2show.setObjectName("btn_2show")
        self.verticalLayout.addWidget(self.btn_2show)
        self.btn_3clus = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_3clus.sizePolicy().hasHeightForWidth())
        self.btn_3clus.setSizePolicy(sizePolicy)
        self.btn_3clus.setMinimumSize(QtCore.QSize(0, 0))
        self.btn_3clus.setStyleSheet("QPushButton{\n"
" image-position: left;\n"
"\n"
"padding-right: 15px;\n"
"    image: url(:/images/resources/负荷聚类.svg);\n"
"\n"
"background-color: rgba(18, 107, 214,100);\n"
"  \n"
"                   font:bold 18px;                       \n"
"                   color:rgba(255,255,255,100);                \n"
"                   padding:20px; \n"
"\n"
"}\n"
"\n"
"\n"
"\n"
" QPushButton:hover{\n"
"                   background-color:rgb(200,225,255);\n"
"                   border-color:rgba(255,255,255,200);\n"
"                   color:rgba(0,0,0,200);\n"
"                font:bold 22px;\n"
"                   }")
        self.btn_3clus.setObjectName("btn_3clus")
        self.verticalLayout.addWidget(self.btn_3clus)
        self.btn_4fore = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_4fore.sizePolicy().hasHeightForWidth())
        self.btn_4fore.setSizePolicy(sizePolicy)
        self.btn_4fore.setStyleSheet("QPushButton{\n"
" image-position: left;\n"
"                       padding-right: 15px;\n"
"    image: url(:/images/resources/负荷预测.svg);\n"
"\n"
"background-color: rgba(18, 107, 214,100);\n"
"  \n"
"                   font:bold 18px;                       \n"
"                   color:rgba(255,255,255,100);                \n"
"                   padding:20px; \n"
"\n"
"}\n"
"\n"
"\n"
"\n"
" QPushButton:hover{\n"
"                   background-color:rgb(200,225,255);\n"
"                   border-color:rgba(255,255,255,200);\n"
"                   color:rgba(0,0,0,200);\n"
"                font:bold 24px;\n"
"                   }")
        self.btn_4fore.setObjectName("btn_4fore")
        self.verticalLayout.addWidget(self.btn_4fore)
        self.text_message = QtWidgets.QTextEdit(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.text_message.setFont(font)
        self.text_message.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.text_message.setStyleSheet("background-color: rgba(255, 255, 255,0);\n"
"font:15px;                       \n"
"color:rgba(255,255,255,200);   ")
        self.text_message.setTextInteractionFlags(QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.text_message.setObjectName("text_message")
        self.verticalLayout.addWidget(self.text_message)
        self.btn_help = QtWidgets.QPushButton(self.groupBox)
        self.btn_help.setStyleSheet("QPushButton{\n"
"image-position: center;                   \n"
"padding-right: 1px;\n"
"image: url(:/images/resources/帮助中心.png);\n"
"background-color: rgba(255, 255, 255,0);\n"
"font:18px;\n"
"color:rgba(255,255,255,100)\n"
"}\n"
"\n"
" QPushButton:hover{\n"
"color:rgba(0,0,0,200);\n"
"font:18px;                   \n"
"}\n"
"")
        self.btn_help.setObjectName("btn_help")
        self.verticalLayout.addWidget(self.btn_help)
        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout.setStretch(1, 1)
        self.verticalLayout.setStretch(2, 1)
        self.verticalLayout.setStretch(3, 1)
        self.verticalLayout.setStretch(4, 5)
        self.gridLayout.addWidget(self.groupBox, 0, 0, 1, 1)
        self.gridLayout.setRowStretch(0, 1)
        self.gridLayout_3.addLayout(self.gridLayout, 0, 1, 1, 1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setStyleSheet("background-color: rgb(255, 255, 255,0);")
        self.stackedWidget.setObjectName("stackedWidget")
        self.page0 = QtWidgets.QWidget()
        self.page0.setObjectName("page0")
        self.gridLayout_26 = QtWidgets.QGridLayout(self.page0)
        self.gridLayout_26.setObjectName("gridLayout_26")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_26.addItem(spacerItem, 0, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_26.addItem(spacerItem1, 0, 2, 1, 1)
        self.p0_textBrowser = QtWidgets.QTextBrowser(self.page0)
        self.p0_textBrowser.setStyleSheet("background-color: rgba(0, 0, 0,100);\n"
"border-style:inset;                  \n"
"border-width:3px;                    \n"
"border-radius:5px;                   \n"
"border-color:rgba(200,200,255,200);   \n"
"")
        self.p0_textBrowser.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.p0_textBrowser.setFrameShadow(QtWidgets.QFrame.Plain)
        self.p0_textBrowser.setLineWidth(0)
        self.p0_textBrowser.setLineWrapMode(QtWidgets.QTextEdit.WidgetWidth)
        self.p0_textBrowser.setCursorWidth(4)
        self.p0_textBrowser.setObjectName("p0_textBrowser")
        self.gridLayout_26.addWidget(self.p0_textBrowser, 0, 1, 1, 1)
        self.gridLayout_26.setColumnStretch(0, 1)
        self.gridLayout_26.setColumnStretch(1, 5)
        self.gridLayout_26.setColumnStretch(2, 1)
        self.stackedWidget.addWidget(self.page0)
        self.page1 = QtWidgets.QWidget()
        self.page1.setStyleSheet("")
        self.page1.setObjectName("page1")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.page1)
        self.gridLayout_4.setObjectName("gridLayout_4")
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem2, 0, 2, 1, 1)
        self.p1_groupBox = QtWidgets.QGroupBox(self.page1)
        self.p1_groupBox.setStyleSheet("QGroupBox{\n"
"                  padding-right: 15px;\n"
"                   border-style:inset;                  \n"
"                   border-width:5px;                    \n"
"                   border-radius:5px;                   \n"
"                   border-color:rgb(255,255,255);   \n"
"                   font:bold 18px;                       \n"
"                   color:rgb(255,255,255);                \n"
"                   padding:6px; \n"
"}")
        self.p1_groupBox.setAlignment(QtCore.Qt.AlignCenter)
        self.p1_groupBox.setFlat(True)
        self.p1_groupBox.setObjectName("p1_groupBox")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.p1_groupBox)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.groupBox_10 = QtWidgets.QGroupBox(self.p1_groupBox)
        self.groupBox_10.setStyleSheet("QGroupBox{\n"
"                  padding-right: 15px;\n"
"                   border-style:inset;                  \n"
"                   border-width:1px;                    \n"
"                   border-radius:5px;                   \n"
"                   border-color:rgb(255,255,255);   \n"
"                   font: 18px;                       \n"
"                   color:rgb(2,2,2);                \n"
"                   padding:6px; \n"
"}\n"
"\n"
"QRadioButton{\n"
"font: 18px;                       \n"
"color:rgb(2,2,2);                \n"
"padding:6px; \n"
"}\n"
"\n"
" \n"
"QComboBox{\n"
"background-color: rgba(255, 255, 255,10);\n"
"border:1px solid rgba(228,228,228,100);\n"
"border-radius:5px 5px 0px 0px;\n"
"font-size:18px;\n"
"}\n"
"\n"
"\n"
"QComboBox QAbstractItemView {\n"
"    outline: 0px solid gray;   /* 选定项的虚框 */\n"
"    border: 1px solid raga(228,228,228,100);   /* 整个下拉窗体的边框 */\n"
"    color: blue;\n"
"    background-color: white;   /* 整个下拉窗体的背景色 */\n"
"    selection-background-color: lightblue;   /* 整个下拉窗体被选中项的背景色 */\n"
"}")
        self.groupBox_10.setObjectName("groupBox_10")
        self.gridLayout_24 = QtWidgets.QGridLayout(self.groupBox_10)
        self.gridLayout_24.setObjectName("gridLayout_24")
        self.p1_cb_paixu = QtWidgets.QComboBox(self.groupBox_10)
        self.p1_cb_paixu.setStyleSheet("")
        self.p1_cb_paixu.setObjectName("p1_cb_paixu")
        self.p1_cb_paixu.addItem("")
        self.p1_cb_paixu.addItem("")
        self.p1_cb_paixu.addItem("")
        self.p1_cb_paixu.addItem("")
        self.gridLayout_24.addWidget(self.p1_cb_paixu, 0, 0, 2, 1)
        self.p1_rb_paixu_zheng = QtWidgets.QRadioButton(self.groupBox_10)
        self.p1_rb_paixu_zheng.setStyleSheet("")
        self.p1_rb_paixu_zheng.setChecked(True)
        self.p1_rb_paixu_zheng.setObjectName("p1_rb_paixu_zheng")
        self.gridLayout_24.addWidget(self.p1_rb_paixu_zheng, 0, 1, 1, 1)
        self.p1_rb_paixu_fan = QtWidgets.QRadioButton(self.groupBox_10)
        self.p1_rb_paixu_fan.setStyleSheet("")
        self.p1_rb_paixu_fan.setObjectName("p1_rb_paixu_fan")
        self.gridLayout_24.addWidget(self.p1_rb_paixu_fan, 1, 1, 1, 1)
        self.gridLayout_24.setColumnStretch(0, 2)
        self.gridLayout_24.setColumnStretch(1, 1)
        self.gridLayout_10.addWidget(self.groupBox_10, 0, 2, 1, 2)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_10.addItem(spacerItem3, 1, 5, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_10.addItem(spacerItem4, 0, 5, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_10.addItem(spacerItem5, 3, 1, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_10.addItem(spacerItem6, 3, 3, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_10.addItem(spacerItem7, 3, 2, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_10.addItem(spacerItem8, 3, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.p1_groupBox)
        self.label_8.setStyleSheet("QLabel{\n"
"font:13px;                       \n"
"color:rgba(0,0,0,100);                \n"
"}")
        self.label_8.setObjectName("label_8")
        self.gridLayout_10.addWidget(self.label_8, 2, 0, 1, 4)
        self.groupBox_6 = QtWidgets.QGroupBox(self.p1_groupBox)
        self.groupBox_6.setStyleSheet("QGroupBox{\n"
"                  padding-right: 15px;\n"
"                   border-style:inset;                  \n"
"                   border-width:1px;                    \n"
"                   border-radius:5px;                   \n"
"                   border-color:rgb(255,255,255);   \n"
"                   font: 18px;                       \n"
"                   color:rgb(2,2,2);                \n"
"                   padding:6px; \n"
"}\n"
"QLabel{\n"
"font:18px;                       \n"
"color:rgb(2,2,2);                \n"
"}\n"
"\n"
"QSpinBox{\n"
"padding-right: 15px; /* make room for the arrows */\n"
"border:1px solid rgba(228,228,228,100);\n"
"border-radius:5px;       \n"
"  \n"
"background-color: rgba(255, 255, 255,10);\n"
"font:18px;      \n"
"color:rgb(2,2,2);\n"
"} \n"
"\n"
"QSpinBox::up-button {\n"
"border-image: url(:/images/resources/spinbox-up.png);\n"
"}\n"
"\n"
"QSpinBox::down-button {\n"
"border-image: url(:/images/resources/spinbox-down.png);\n"
"}\n"
"\n"
"QSpinBox::up-button:pressed {\n"
"margin-top:3px;\n"
"}\n"
"\n"
"QSpinBox::down-button:pressed {\n"
"margin-bottom:3px;\n"
"}\n"
"")
        self.groupBox_6.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.groupBox_6.setFlat(False)
        self.groupBox_6.setObjectName("groupBox_6")
        self.gridLayout_20 = QtWidgets.QGridLayout(self.groupBox_6)
        self.gridLayout_20.setObjectName("gridLayout_20")
        self.p1_sb_month = QtWidgets.QSpinBox(self.groupBox_6)
        self.p1_sb_month.setMaximum(12)
        self.p1_sb_month.setObjectName("p1_sb_month")
        self.gridLayout_20.addWidget(self.p1_sb_month, 0, 7, 1, 1)
        self.p1_sb_day = QtWidgets.QSpinBox(self.groupBox_6)
        self.p1_sb_day.setMaximum(31)
        self.p1_sb_day.setObjectName("p1_sb_day")
        self.gridLayout_20.addWidget(self.p1_sb_day, 0, 10, 1, 1)
        self.label_0 = QtWidgets.QLabel(self.groupBox_6)
        self.label_0.setStyleSheet("")
        self.label_0.setObjectName("label_0")
        self.gridLayout_20.addWidget(self.label_0, 0, 2, 1, 1)
        self.label_1 = QtWidgets.QLabel(self.groupBox_6)
        self.label_1.setStyleSheet("font:16px;                       \n"
"color:rgb(2,2,2);                ")
        self.label_1.setObjectName("label_1")
        self.gridLayout_20.addWidget(self.label_1, 0, 4, 1, 1)
        self.p1_sb_year = QtWidgets.QSpinBox(self.groupBox_6)
        self.p1_sb_year.setMaximum(3000)
        self.p1_sb_year.setSingleStep(1)
        self.p1_sb_year.setProperty("value", 0)
        self.p1_sb_year.setObjectName("p1_sb_year")
        self.gridLayout_20.addWidget(self.p1_sb_year, 0, 3, 1, 1)
        self.p1_sb_zoneid = QtWidgets.QSpinBox(self.groupBox_6)
        self.p1_sb_zoneid.setStyleSheet("")
        self.p1_sb_zoneid.setMaximum(21)
        self.p1_sb_zoneid.setObjectName("p1_sb_zoneid")
        self.gridLayout_20.addWidget(self.p1_sb_zoneid, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox_6)
        self.label_2.setStyleSheet("font:16px;                       \n"
"color:rgb(2,2,2);                ")
        self.label_2.setObjectName("label_2")
        self.gridLayout_20.addWidget(self.label_2, 0, 8, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox_6)
        self.label_3.setStyleSheet("font:16px;                       \n"
"color:rgb(2,2,2);                ")
        self.label_3.setObjectName("label_3")
        self.gridLayout_20.addWidget(self.label_3, 0, 11, 1, 1)
        self.gridLayout_10.addWidget(self.groupBox_6, 0, 0, 1, 2)
        self.groupBox_9 = QtWidgets.QGroupBox(self.p1_groupBox)
        self.groupBox_9.setStyleSheet("QGroupBox{\n"
"                  padding-right: 15px;\n"
"                   border-style:inset;                  \n"
"                   border-width:1px;                    \n"
"                   border-radius:1px;                   \n"
"                   border-color:rgb(255,255,255);   \n"
"                   font: 18px;                       \n"
"                   color:rgb(2,2,2);                \n"
"                   padding:6px; \n"
"}\n"
"\n"
"QPushButton{\n"
" image-position: left;\n"
"\n"
"                  padding-right: 15px;\n"
"                   border-style:inset;                  \n"
"                   border-width:2px;                    \n"
"                   border-radius:1px;                   \n"
"                   border-color:rgba(255,255,255,100);   \n"
"                   font:18px;                       \n"
"                   color:rgb(2,2,2);                \n"
"                   padding:6px; \n"
"\n"
"}\n"
" QPushButton:hover{\n"
"                   background-color:rgb(200,225,255);\n"
"                   border-color:rgba(255,255,255,200);\n"
"                   color:rgba(0,0,0,200);\n"
"font:bold 20px;\n"
"                   }\n"
"\n"
"QLineEdit{\n"
"border:1px solid rgba(228,228,228,100);\n"
"font:18px;                       \n"
"color:rgba(5,5,50,1);     \n"
"} ")
        self.groupBox_9.setObjectName("groupBox_9")
        self.gridLayout_23 = QtWidgets.QGridLayout(self.groupBox_9)
        self.gridLayout_23.setObjectName("gridLayout_23")
        self.p1_lineEdit_sql = QtWidgets.QLineEdit(self.groupBox_9)
        self.p1_lineEdit_sql.setStyleSheet("")
        self.p1_lineEdit_sql.setText("")
        self.p1_lineEdit_sql.setObjectName("p1_lineEdit_sql")
        self.gridLayout_23.addWidget(self.p1_lineEdit_sql, 0, 0, 1, 1)
        self.p1_pushButton_search = QtWidgets.QPushButton(self.groupBox_9)
        self.p1_pushButton_search.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.p1_pushButton_search.setStyleSheet("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/images/resources/查询.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.p1_pushButton_search.setIcon(icon1)
        self.p1_pushButton_search.setIconSize(QtCore.QSize(20, 20))
        self.p1_pushButton_search.setAutoRepeat(False)
        self.p1_pushButton_search.setObjectName("p1_pushButton_search")
        self.gridLayout_23.addWidget(self.p1_pushButton_search, 0, 1, 1, 1)
        self.gridLayout_23.setColumnStretch(0, 5)
        self.gridLayout_23.setColumnStretch(1, 1)
        self.gridLayout_10.addWidget(self.groupBox_9, 1, 0, 1, 2)
        self.groupBox_8 = QtWidgets.QGroupBox(self.p1_groupBox)
        self.groupBox_8.setStyleSheet("QGroupBox{\n"
"                  padding-right: 15px;\n"
"                   border-style:inset;                  \n"
"                   border-width:1px;                    \n"
"                   border-radius:1px;                   \n"
"                   border-color:rgb(255,255,255);   \n"
"                   font: 18px;                       \n"
"                   color:rgb(2,2,2);                \n"
"                   padding:6px; \n"
"}\n"
"\n"
"QPushButton{\n"
" image-position: left;\n"
"\n"
"                  padding-right: 15px;\n"
"                   border-style:inset;                  \n"
"                   border-width:2px;                    \n"
"                   border-radius:1px;                   \n"
"                   border-color:rgba(255,255,255,100);   \n"
"                   font:18px;                       \n"
"                   color:rgb(2,2,2);                \n"
"                   padding:6px; \n"
"\n"
"}\n"
" QPushButton:hover{\n"
"                   background-color:rgb(200,225,255);\n"
"                   border-color:rgba(255,255,255,200);\n"
"                   color:rgba(0,0,0,200);\n"
"font:bold 20px;\n"
"                   }")
        self.groupBox_8.setObjectName("groupBox_8")
        self.gridLayout_22 = QtWidgets.QGridLayout(self.groupBox_8)
        self.gridLayout_22.setObjectName("gridLayout_22")
        self.p1_btn_add = QtWidgets.QPushButton(self.groupBox_8)
        self.p1_btn_add.setStyleSheet("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/images/resources/增加.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.p1_btn_add.setIcon(icon2)
        self.p1_btn_add.setObjectName("p1_btn_add")
        self.gridLayout_22.addWidget(self.p1_btn_add, 0, 0, 1, 1)
        self.p1_btn_save = QtWidgets.QPushButton(self.groupBox_8)
        self.p1_btn_save.setStyleSheet("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/images/resources/保存.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.p1_btn_save.setIcon(icon3)
        self.p1_btn_save.setObjectName("p1_btn_save")
        self.gridLayout_22.addWidget(self.p1_btn_save, 0, 2, 1, 1)
        self.p1_btn_del = QtWidgets.QPushButton(self.groupBox_8)
        self.p1_btn_del.setStyleSheet("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/images/resources/删除.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.p1_btn_del.setIcon(icon4)
        self.p1_btn_del.setObjectName("p1_btn_del")
        self.gridLayout_22.addWidget(self.p1_btn_del, 0, 1, 1, 1)
        self.gridLayout_10.addWidget(self.groupBox_8, 1, 2, 1, 2)
        self.gridLayout_10.setColumnStretch(0, 2)
        self.gridLayout_10.setColumnStretch(1, 1)
        self.gridLayout_10.setColumnStretch(2, 1)
        self.gridLayout_10.setColumnStretch(3, 1)
        self.gridLayout_10.setRowStretch(0, 1)
        self.gridLayout_10.setRowStretch(1, 1)
        self.gridLayout_4.addWidget(self.p1_groupBox, 1, 0, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem9, 1, 2, 1, 1)
        self.p1_tableView = QtWidgets.QTableView(self.page1)
        self.p1_tableView.setStyleSheet("")
        self.p1_tableView.setObjectName("p1_tableView")
        self.gridLayout_4.addWidget(self.p1_tableView, 0, 0, 1, 1)
        self.gridLayout_4.setRowStretch(0, 2)
        self.gridLayout_4.setRowStretch(1, 1)
        self.stackedWidget.addWidget(self.page1)
        self.page2 = QtWidgets.QWidget()
        self.page2.setObjectName("page2")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.page2)
        self.gridLayout_5.setObjectName("gridLayout_5")
        spacerItem10 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem10, 0, 2, 1, 1)
        spacerItem11 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem11, 1, 2, 1, 1)
        self.p2_groupBox = QtWidgets.QGroupBox(self.page2)
        self.p2_groupBox.setStyleSheet("QGroupBox{\n"
"                  padding-right: 15px;\n"
"                   border-style:inset;                  \n"
"                   border-width:5px;                    \n"
"                   border-radius:5px;                   \n"
"                   border-color:rgb(255,255,255);   \n"
"                   font:bold 18px;                       \n"
"                   color:rgba(255,255,255,255);                \n"
"                   padding:6px; \n"
"}")
        self.p2_groupBox.setAlignment(QtCore.Qt.AlignCenter)
        self.p2_groupBox.setFlat(True)
        self.p2_groupBox.setObjectName("p2_groupBox")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.p2_groupBox)
        self.gridLayout_11.setObjectName("gridLayout_11")
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_11.addItem(spacerItem12, 2, 5, 1, 1)
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_11.addItem(spacerItem13, 2, 4, 1, 1)
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_11.addItem(spacerItem14, 2, 0, 1, 1)
        spacerItem15 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_11.addItem(spacerItem15, 2, 2, 1, 1)
        self.p2_groupBox_zoonid = QtWidgets.QGroupBox(self.p2_groupBox)
        self.p2_groupBox_zoonid.setStyleSheet("QGroupBox{\n"
"                  padding-right: 15px;\n"
"                   border-style:inset;                  \n"
"                   border-width:1px;                    \n"
"                   border-radius:5px;                   \n"
"                   border-color:rgb(255,255,255);   \n"
"                   font: 18px;                       \n"
"                   color:rgb(2,2,2);                \n"
"                   padding:6px; \n"
"}\n"
"QCheckBox::indicator::unchecked {\n"
"    image: url(:/images/resources/checkbox_unchecked.png);\n"
"width:25px;\n"
"height:25px;\n"
"\n"
"}\n"
"QCheckBox::indicator::checked {\n"
"    image: url(:/images/resources/checkbox_checked.png);\n"
"width:25px;\n"
"height:25px\n"
"}\n"
"\n"
"\n"
"\n"
"")
        self.p2_groupBox_zoonid.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.p2_groupBox_zoonid.setFlat(False)
        self.p2_groupBox_zoonid.setCheckable(False)
        self.p2_groupBox_zoonid.setObjectName("p2_groupBox_zoonid")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.p2_groupBox_zoonid)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.p2_cb_6 = QtWidgets.QCheckBox(self.p2_groupBox_zoonid)
        self.p2_cb_6.setObjectName("p2_cb_6")
        self.gridLayout_7.addWidget(self.p2_cb_6, 1, 0, 1, 1)
        self.p2_cb_14 = QtWidgets.QCheckBox(self.p2_groupBox_zoonid)
        self.p2_cb_14.setObjectName("p2_cb_14")
        self.gridLayout_7.addWidget(self.p2_cb_14, 2, 3, 1, 1)
        self.p2_cb_17 = QtWidgets.QCheckBox(self.p2_groupBox_zoonid)
        self.p2_cb_17.setObjectName("p2_cb_17")
        self.gridLayout_7.addWidget(self.p2_cb_17, 3, 1, 1, 1)
        self.p2_cb_5 = QtWidgets.QCheckBox(self.p2_groupBox_zoonid)
        self.p2_cb_5.setObjectName("p2_cb_5")
        self.gridLayout_7.addWidget(self.p2_cb_5, 0, 4, 1, 1)
        self.p2_cb_15 = QtWidgets.QCheckBox(self.p2_groupBox_zoonid)
        self.p2_cb_15.setObjectName("p2_cb_15")
        self.gridLayout_7.addWidget(self.p2_cb_15, 2, 4, 1, 1)
        self.p2_cb_20 = QtWidgets.QCheckBox(self.p2_groupBox_zoonid)
        self.p2_cb_20.setObjectName("p2_cb_20")
        self.gridLayout_7.addWidget(self.p2_cb_20, 3, 4, 1, 1)
        self.p2_cb_13 = QtWidgets.QCheckBox(self.p2_groupBox_zoonid)
        self.p2_cb_13.setObjectName("p2_cb_13")
        self.gridLayout_7.addWidget(self.p2_cb_13, 2, 2, 1, 1)
        self.p2_cb_4 = QtWidgets.QCheckBox(self.p2_groupBox_zoonid)
        self.p2_cb_4.setObjectName("p2_cb_4")
        self.gridLayout_7.addWidget(self.p2_cb_4, 0, 3, 1, 1)
        self.p2_cb_19 = QtWidgets.QCheckBox(self.p2_groupBox_zoonid)
        self.p2_cb_19.setObjectName("p2_cb_19")
        self.gridLayout_7.addWidget(self.p2_cb_19, 3, 3, 1, 1)
        self.p2_cb_18 = QtWidgets.QCheckBox(self.p2_groupBox_zoonid)
        self.p2_cb_18.setObjectName("p2_cb_18")
        self.gridLayout_7.addWidget(self.p2_cb_18, 3, 2, 1, 1)
        self.p2_cb_1 = QtWidgets.QCheckBox(self.p2_groupBox_zoonid)
        self.p2_cb_1.setObjectName("p2_cb_1")
        self.gridLayout_7.addWidget(self.p2_cb_1, 0, 0, 1, 1)
        self.p2_cb_11 = QtWidgets.QCheckBox(self.p2_groupBox_zoonid)
        self.p2_cb_11.setObjectName("p2_cb_11")
        self.gridLayout_7.addWidget(self.p2_cb_11, 2, 0, 1, 1)
        self.p2_cb_2 = QtWidgets.QCheckBox(self.p2_groupBox_zoonid)
        self.p2_cb_2.setObjectName("p2_cb_2")
        self.gridLayout_7.addWidget(self.p2_cb_2, 0, 1, 1, 1)
        self.p2_cb_16 = QtWidgets.QCheckBox(self.p2_groupBox_zoonid)
        self.p2_cb_16.setObjectName("p2_cb_16")
        self.gridLayout_7.addWidget(self.p2_cb_16, 3, 0, 1, 1)
        self.p2_cb_8 = QtWidgets.QCheckBox(self.p2_groupBox_zoonid)
        self.p2_cb_8.setObjectName("p2_cb_8")
        self.gridLayout_7.addWidget(self.p2_cb_8, 1, 2, 1, 1)
        self.p2_cb_12 = QtWidgets.QCheckBox(self.p2_groupBox_zoonid)
        self.p2_cb_12.setObjectName("p2_cb_12")
        self.gridLayout_7.addWidget(self.p2_cb_12, 2, 1, 1, 1)
        self.p2_cb_9 = QtWidgets.QCheckBox(self.p2_groupBox_zoonid)
        self.p2_cb_9.setObjectName("p2_cb_9")
        self.gridLayout_7.addWidget(self.p2_cb_9, 1, 3, 1, 1)
        self.p2_cb_10 = QtWidgets.QCheckBox(self.p2_groupBox_zoonid)
        self.p2_cb_10.setObjectName("p2_cb_10")
        self.gridLayout_7.addWidget(self.p2_cb_10, 1, 4, 1, 1)
        self.p2_cb_3 = QtWidgets.QCheckBox(self.p2_groupBox_zoonid)
        self.p2_cb_3.setStyleSheet("")
        self.p2_cb_3.setIconSize(QtCore.QSize(5, 5))
        self.p2_cb_3.setObjectName("p2_cb_3")
        self.gridLayout_7.addWidget(self.p2_cb_3, 0, 2, 1, 1)
        self.p2_cb_7 = QtWidgets.QCheckBox(self.p2_groupBox_zoonid)
        self.p2_cb_7.setObjectName("p2_cb_7")
        self.gridLayout_7.addWidget(self.p2_cb_7, 1, 1, 1, 1)
        self.gridLayout_7.setRowStretch(0, 1)
        self.gridLayout_7.setRowStretch(3, 5)
        self.gridLayout_11.addWidget(self.p2_groupBox_zoonid, 1, 0, 1, 7)
        spacerItem16 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_11.addItem(spacerItem16, 2, 3, 1, 1)
        spacerItem17 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_11.addItem(spacerItem17, 2, 1, 1, 1)
        spacerItem18 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_11.addItem(spacerItem18, 0, 7, 1, 1)
        spacerItem19 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_11.addItem(spacerItem19, 1, 7, 1, 1)
        spacerItem20 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_11.addItem(spacerItem20, 2, 7, 1, 1)
        self.groupBox_7 = QtWidgets.QGroupBox(self.p2_groupBox)
        self.groupBox_7.setStyleSheet("QGroupBox{\n"
"                  padding-right: 15px;\n"
"                   border-style:inset;                  \n"
"                   border-width:1px;                    \n"
"                   border-radius:5px;                   \n"
"                   border-color:rgb(255,255,255);   \n"
"                   font: 18px;                       \n"
"                   color:rgb(2,2,2);                \n"
"                   padding:6px; \n"
"}\n"
"QLabel{\n"
"font:18px;                       \n"
"color:rgb(2,2,2);                \n"
"}\n"
"\n"
"QSpinBox{\n"
"padding-right: 15px; /* make room for the arrows */\n"
"border:1px solid rgba(228,228,228,100);\n"
"border-radius:5px;       \n"
"  \n"
"background-color: rgba(255, 255, 255,10);\n"
"font:18px;      \n"
"color:rgb(2,2,2);\n"
"} \n"
"\n"
"QSpinBox::up-button {\n"
"border-image: url(:/images/resources/spinbox-up.png);\n"
"}\n"
"\n"
"QSpinBox::down-button {\n"
"border-image: url(:/images/resources/spinbox-down.png);\n"
"}\n"
"\n"
"QSpinBox::up-button:pressed {\n"
"margin-top:3px;\n"
"}\n"
"\n"
"QSpinBox::down-button:pressed {\n"
"margin-bottom:3px;\n"
"}\n"
"")
        self.groupBox_7.setObjectName("groupBox_7")
        self.gridLayout_21 = QtWidgets.QGridLayout(self.groupBox_7)
        self.gridLayout_21.setObjectName("gridLayout_21")
        self.p2_sb_day = QtWidgets.QSpinBox(self.groupBox_7)
        self.p2_sb_day.setMaximum(31)
        self.p2_sb_day.setProperty("value", 1)
        self.p2_sb_day.setObjectName("p2_sb_day")
        self.gridLayout_21.addWidget(self.p2_sb_day, 1, 6, 1, 1)
        self.p2_sb_month = QtWidgets.QSpinBox(self.groupBox_7)
        self.p2_sb_month.setMaximum(12)
        self.p2_sb_month.setProperty("value", 1)
        self.p2_sb_month.setObjectName("p2_sb_month")
        self.gridLayout_21.addWidget(self.p2_sb_month, 1, 4, 1, 1)
        self.p2_sb_year = QtWidgets.QSpinBox(self.groupBox_7)
        self.p2_sb_year.setMaximum(3000)
        self.p2_sb_year.setProperty("value", 2004)
        self.p2_sb_year.setObjectName("p2_sb_year")
        self.gridLayout_21.addWidget(self.p2_sb_year, 1, 2, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox_7)
        self.label_4.setObjectName("label_4")
        self.gridLayout_21.addWidget(self.label_4, 1, 3, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox_7)
        self.label_5.setObjectName("label_5")
        self.gridLayout_21.addWidget(self.label_5, 1, 5, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.groupBox_7)
        self.label_6.setObjectName("label_6")
        self.gridLayout_21.addWidget(self.label_6, 1, 7, 1, 1)
        self.gridLayout_11.addWidget(self.groupBox_7, 0, 0, 1, 5)
        self.groupBox_11 = QtWidgets.QGroupBox(self.p2_groupBox)
        self.groupBox_11.setStyleSheet("QGroupBox{\n"
"                  padding-right: 15px;\n"
"                   border-style:inset;                  \n"
"                   border-width:1px;                    \n"
"                   border-radius:5px;                   \n"
"                   border-color:rgb(255,255,255);   \n"
"                   font: 18px;                       \n"
"                   color:rgb(2,2,2);                \n"
"                   padding:10px; \n"
"}\n"
"QLabel{\n"
"font:12px;                       \n"
"color:rgb(2,2,2);                \n"
"}\n"
"\n"
"QCheckBox{\n"
"font:15px;                       \n"
"color:rgb(2,2,2); \n"
"}\n"
"\n"
"QCheckBox::indicator::unchecked {\n"
"image: url(:/images/resources/btn_unchecked.png);\n"
"width:15px;\n"
"height:15px;\n"
"\n"
"\n"
"}\n"
"QCheckBox::indicator::checked {\n"
"    image: url(:/images/resources/btn_checked.png);\n"
"width:15px;\n"
"height:15px\n"
"}\n"
"")
        self.groupBox_11.setObjectName("groupBox_11")
        self.gridLayout_25 = QtWidgets.QGridLayout(self.groupBox_11)
        self.gridLayout_25.setObjectName("gridLayout_25")
        self.p2_checkBox_data = QtWidgets.QCheckBox(self.groupBox_11)
        self.p2_checkBox_data.setObjectName("p2_checkBox_data")
        self.gridLayout_25.addWidget(self.p2_checkBox_data, 0, 0, 1, 1)
        self.p2_checkBox_dhua = QtWidgets.QCheckBox(self.groupBox_11)
        self.p2_checkBox_dhua.setObjectName("p2_checkBox_dhua")
        self.gridLayout_25.addWidget(self.p2_checkBox_dhua, 1, 0, 1, 1)
        self.gridLayout_25.setRowStretch(0, 1)
        self.gridLayout_25.setRowStretch(1, 1)
        self.gridLayout_11.addWidget(self.groupBox_11, 0, 5, 1, 1)
        self.gridLayout_11.setRowStretch(0, 1)
        self.gridLayout_11.setRowStretch(1, 1)
        self.gridLayout_5.addWidget(self.p2_groupBox, 1, 0, 1, 1)
        self.p2_widget = QtWidgets.QWidget(self.page2)
        self.p2_widget.setObjectName("p2_widget")
        self.p2_verticalLayout = QtWidgets.QVBoxLayout(self.p2_widget)
        self.p2_verticalLayout.setObjectName("p2_verticalLayout")
        self.gridLayout_5.addWidget(self.p2_widget, 0, 0, 1, 1)
        self.gridLayout_5.setColumnStretch(0, 1)
        self.gridLayout_5.setRowStretch(0, 2)
        self.gridLayout_5.setRowStretch(1, 1)
        self.stackedWidget.addWidget(self.page2)
        self.page3 = QtWidgets.QWidget()
        self.page3.setObjectName("page3")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.page3)
        self.gridLayout_6.setObjectName("gridLayout_6")
        spacerItem21 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_6.addItem(spacerItem21, 1, 1, 1, 1)
        spacerItem22 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_6.addItem(spacerItem22, 0, 1, 1, 1)
        self.p3_groupBox = QtWidgets.QGroupBox(self.page3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.p3_groupBox.sizePolicy().hasHeightForWidth())
        self.p3_groupBox.setSizePolicy(sizePolicy)
        self.p3_groupBox.setStyleSheet("QGroupBox{\n"
"                  padding-right: 15px;\n"
"                   border-style:inset;                  \n"
"                   border-width:5px;                    \n"
"                   border-radius:5px;                   \n"
"                   border-color:rgb(255,255,255);   \n"
"                   font:bold 18px;                       \n"
"                   color:rgba(255,255,255,255);                \n"
"                   padding:6px; \n"
"}")
        self.p3_groupBox.setAlignment(QtCore.Qt.AlignCenter)
        self.p3_groupBox.setFlat(True)
        self.p3_groupBox.setObjectName("p3_groupBox")
        self.gridLayout_18 = QtWidgets.QGridLayout(self.p3_groupBox)
        self.gridLayout_18.setObjectName("gridLayout_18")
        self.p3_btn_saveResult = QtWidgets.QPushButton(self.p3_groupBox)
        self.p3_btn_saveResult.setStyleSheet("QPushButton{\n"
" image-position: left;\n"
"\n"
"                  padding-right: 15px;\n"
"                   border-style:inset;                  \n"
"                   border-width:2px;                    \n"
"                   border-radius:1px;                   \n"
"                   border-color:rgba(255,255,255,100);   \n"
"                   font:18px;                       \n"
"                   color:rgb(2,2,2);                \n"
"                   padding:6px; \n"
"\n"
"}\n"
" QPushButton:hover{\n"
"                   background-color:rgb(200,225,255);\n"
"                   border-color:rgba(255,255,255,200);\n"
"                   color:rgba(0,0,0,200);\n"
"font:bold 20px;\n"
"                   }")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/images/resources/导出.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.p3_btn_saveResult.setIcon(icon5)
        self.p3_btn_saveResult.setObjectName("p3_btn_saveResult")
        self.gridLayout_18.addWidget(self.p3_btn_saveResult, 2, 2, 1, 1)
        spacerItem23 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_18.addItem(spacerItem23, 3, 2, 1, 1)
        self.p3_result = QtWidgets.QTextEdit(self.p3_groupBox)
        self.p3_result.setStyleSheet("font:15px;                       \n"
"color:rgba(255,255,255,200);                ")
        self.p3_result.setTextInteractionFlags(QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.p3_result.setObjectName("p3_result")
        self.gridLayout_18.addWidget(self.p3_result, 0, 2, 2, 1)
        spacerItem24 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_18.addItem(spacerItem24, 3, 0, 1, 1)
        spacerItem25 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_18.addItem(spacerItem25, 3, 1, 1, 1)
        self.groupBox_4 = QtWidgets.QGroupBox(self.p3_groupBox)
        self.groupBox_4.setStyleSheet("QGroupBox{\n"
"                  padding-right: 15px;\n"
"                   border-style:inset;                  \n"
"                   border-width:1px;                    \n"
"                   border-radius:1px;                   \n"
"                   border-color:rgb(255,255,255);   \n"
"                   font: 18px;                       \n"
"                   color:rgb(2,2,2);                \n"
"                   padding:6px; \n"
"}\n"
"\n"
"QPushButton{\n"
" image-position: left;\n"
"\n"
"                  padding-right: 15px;\n"
"                   border-style:inset;                  \n"
"                   border-width:2px;                    \n"
"                   border-radius:1px;                   \n"
"                   border-color:rgba(255,255,255,100);   \n"
"                   font:18px;                       \n"
"                   color:rgb(2,2,2);                \n"
"                   padding:6px; \n"
"\n"
"}\n"
" QPushButton:hover{\n"
"                   background-color:rgb(200,225,255);\n"
"                   border-color:rgba(255,255,255,200);\n"
"                   color:rgba(0,0,0,200);\n"
"font:bold 18px;\n"
"                   }")
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.p3_btn1_choose = QtWidgets.QPushButton(self.groupBox_4)
        self.p3_btn1_choose.setStyleSheet("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/images/resources/数据选择器.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.p3_btn1_choose.setIcon(icon6)
        self.p3_btn1_choose.setObjectName("p3_btn1_choose")
        self.gridLayout_12.addWidget(self.p3_btn1_choose, 0, 0, 1, 1)
        self.p3_listWidget = QtWidgets.QListWidget(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.p3_listWidget.sizePolicy().hasHeightForWidth())
        self.p3_listWidget.setSizePolicy(sizePolicy)
        self.p3_listWidget.setProperty("isWrapping", False)
        self.p3_listWidget.setObjectName("p3_listWidget")
        self.gridLayout_12.addWidget(self.p3_listWidget, 0, 1, 1, 1)
        self.gridLayout_18.addWidget(self.groupBox_4, 0, 0, 1, 1)
        self.groupBox_12 = QtWidgets.QGroupBox(self.p3_groupBox)
        self.groupBox_12.setStyleSheet("QGroupBox{\n"
"                  padding-right: 15px;\n"
"                   border-style:inset;                  \n"
"                   border-width:1px;                    \n"
"                   border-radius:5px;                   \n"
"                   border-color:rgb(255,255,255);   \n"
"                   font: 18px;                       \n"
"                   color:rgb(2,2,2);                \n"
"                   padding:6px; \n"
"}\n"
"QLabel{\n"
"font:18px;                       \n"
"color:rgb(2,2,2);                \n"
"}\n"
"\n"
"QCheckBox{\n"
"font:18px;                       \n"
"color:rgb(2,2,2); \n"
"}\n"
"\n"
"QCheckBox::indicator::unchecked {\n"
"image: url(:/images/resources/btn_unchecked.png);\n"
"width:15px;\n"
"height:15px;\n"
"\n"
"\n"
"}\n"
"QCheckBox::indicator::checked {\n"
"    image: url(:/images/resources/btn_checked.png);\n"
"width:15px;\n"
"height:15px\n"
"}\n"
"")
        self.groupBox_12.setObjectName("groupBox_12")
        self.gridLayout_27 = QtWidgets.QGridLayout(self.groupBox_12)
        self.gridLayout_27.setObjectName("gridLayout_27")
        self.p3_checkBox_showAve = QtWidgets.QCheckBox(self.groupBox_12)
        self.p3_checkBox_showAve.setStyleSheet("")
        self.p3_checkBox_showAve.setObjectName("p3_checkBox_showAve")
        self.gridLayout_27.addWidget(self.p3_checkBox_showAve, 0, 0, 1, 1)
        self.gridLayout_18.addWidget(self.groupBox_12, 0, 1, 1, 1)
        self.groupBox_5 = QtWidgets.QGroupBox(self.p3_groupBox)
        self.groupBox_5.setStyleSheet("QGroupBox{\n"
"                  padding-right: 15px;\n"
"                   border-style:inset;                  \n"
"                   border-width:1px;                    \n"
"                   border-radius:5px;                   \n"
"                   border-color:rgb(255,255,255);   \n"
"                   font: 18px;                       \n"
"                   color:rgb(2,2,2);                \n"
"                   padding:6px; \n"
"}\n"
"QLabel{\n"
"font:18px;                       \n"
"color:rgb(2,2,2);                \n"
"}\n"
"\n"
"QSlider::handle:horizontal {\n"
"background-color: rgba(200,200,200,200);\n"
"}\n"
"\n"
"\n"
"QComboBox{\n"
"background-color: rgba(255, 255, 255,10);\n"
"border:1px solid rgba(228,228,228,100);\n"
"border-radius:5px 5px 0px 0px;\n"
"font-size:18px;\n"
"}\n"
"\n"
"\n"
"QComboBox QAbstractItemView {\n"
"    outline: 0px solid gray;   /* 选定项的虚框 */\n"
"    border: 1px solid raga(228,228,228,100);   /* 整个下拉窗体的边框 */\n"
"    color: blue;\n"
"    background-color: white;   /* 整个下拉窗体的背景色 */\n"
"    selection-background-color: lightblue;   /* 整个下拉窗体被选中项的背景色 */\n"
"}")
        self.groupBox_5.setObjectName("groupBox_5")
        self.gridLayout_17 = QtWidgets.QGridLayout(self.groupBox_5)
        self.gridLayout_17.setObjectName("gridLayout_17")
        self.p3_sw_method = QtWidgets.QStackedWidget(self.groupBox_5)
        self.p3_sw_method.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.p3_sw_method.sizePolicy().hasHeightForWidth())
        self.p3_sw_method.setSizePolicy(sizePolicy)
        self.p3_sw_method.setObjectName("p3_sw_method")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.gridLayout_19 = QtWidgets.QGridLayout(self.page)
        self.gridLayout_19.setObjectName("gridLayout_19")
        self.label_13 = QtWidgets.QLabel(self.page)
        self.label_13.setObjectName("label_13")
        self.gridLayout_19.addWidget(self.label_13, 0, 0, 1, 1)
        self.p3_sw_method.addWidget(self.page)
        self.pg1_cnum = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pg1_cnum.sizePolicy().hasHeightForWidth())
        self.pg1_cnum.setSizePolicy(sizePolicy)
        self.pg1_cnum.setObjectName("pg1_cnum")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.pg1_cnum)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.p3_slider_cnum = QtWidgets.QSlider(self.pg1_cnum)
        self.p3_slider_cnum.setMinimum(2)
        self.p3_slider_cnum.setMaximum(20)
        self.p3_slider_cnum.setProperty("value", 3)
        self.p3_slider_cnum.setTracking(True)
        self.p3_slider_cnum.setOrientation(QtCore.Qt.Horizontal)
        self.p3_slider_cnum.setInvertedControls(False)
        self.p3_slider_cnum.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.p3_slider_cnum.setTickInterval(2)
        self.p3_slider_cnum.setObjectName("p3_slider_cnum")
        self.gridLayout_8.addWidget(self.p3_slider_cnum, 0, 1, 1, 1)
        self.p3_label_cnum = QtWidgets.QLabel(self.pg1_cnum)
        self.p3_label_cnum.setObjectName("p3_label_cnum")
        self.gridLayout_8.addWidget(self.p3_label_cnum, 0, 0, 1, 1)
        self.p3_sw_method.addWidget(self.pg1_cnum)
        self.pg2_db = QtWidgets.QWidget()
        self.pg2_db.setObjectName("pg2_db")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.pg2_db)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.p3_slider_minpts = QtWidgets.QSlider(self.pg2_db)
        self.p3_slider_minpts.setMaximum(100)
        self.p3_slider_minpts.setProperty("value", 10)
        self.p3_slider_minpts.setOrientation(QtCore.Qt.Horizontal)
        self.p3_slider_minpts.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.p3_slider_minpts.setObjectName("p3_slider_minpts")
        self.gridLayout_9.addWidget(self.p3_slider_minpts, 3, 1, 1, 1)
        spacerItem26 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_9.addItem(spacerItem26, 1, 3, 1, 1)
        spacerItem27 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_9.addItem(spacerItem27, 2, 3, 1, 1)
        spacerItem28 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_9.addItem(spacerItem28, 3, 3, 1, 1)
        self.p3_slider_eps = QtWidgets.QSlider(self.pg2_db)
        self.p3_slider_eps.setMaximum(100)
        self.p3_slider_eps.setSingleStep(1)
        self.p3_slider_eps.setPageStep(10)
        self.p3_slider_eps.setProperty("value", 10)
        self.p3_slider_eps.setSliderPosition(10)
        self.p3_slider_eps.setOrientation(QtCore.Qt.Horizontal)
        self.p3_slider_eps.setInvertedAppearance(False)
        self.p3_slider_eps.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.p3_slider_eps.setTickInterval(0)
        self.p3_slider_eps.setObjectName("p3_slider_eps")
        self.gridLayout_9.addWidget(self.p3_slider_eps, 1, 1, 1, 1)
        spacerItem29 = QtWidgets.QSpacerItem(20, 9, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_9.addItem(spacerItem29, 0, 3, 1, 1)
        self.p3_label_eps = QtWidgets.QLabel(self.pg2_db)
        self.p3_label_eps.setObjectName("p3_label_eps")
        self.gridLayout_9.addWidget(self.p3_label_eps, 1, 0, 1, 1)
        self.p3_label_minpts = QtWidgets.QLabel(self.pg2_db)
        self.p3_label_minpts.setObjectName("p3_label_minpts")
        self.gridLayout_9.addWidget(self.p3_label_minpts, 3, 0, 1, 1)
        self.p3_sw_method.addWidget(self.pg2_db)
        self.gridLayout_17.addWidget(self.p3_sw_method, 0, 1, 1, 1)
        self.p3_cb_method = QtWidgets.QComboBox(self.groupBox_5)
        self.p3_cb_method.setStyleSheet("")
        self.p3_cb_method.setObjectName("p3_cb_method")
        self.p3_cb_method.addItem("")
        self.p3_cb_method.addItem("")
        self.p3_cb_method.addItem("")
        self.p3_cb_method.addItem("")
        self.p3_cb_method.addItem("")
        self.p3_cb_method.addItem("")
        self.gridLayout_17.addWidget(self.p3_cb_method, 0, 0, 1, 1)
        self.gridLayout_18.addWidget(self.groupBox_5, 1, 0, 2, 2)
        self.gridLayout_18.setColumnStretch(0, 2)
        self.gridLayout_18.setColumnStretch(1, 1)
        self.gridLayout_18.setColumnStretch(2, 3)
        self.gridLayout_18.setRowStretch(0, 1)
        self.gridLayout_18.setRowStretch(1, 1)
        self.gridLayout_18.setRowStretch(2, 1)
        self.gridLayout_6.addWidget(self.p3_groupBox, 1, 0, 1, 1)
        self.p3_widget = QtWidgets.QWidget(self.page3)
        self.p3_widget.setStyleSheet("")
        self.p3_widget.setObjectName("p3_widget")
        self.p3_verticalLayout = QtWidgets.QVBoxLayout(self.p3_widget)
        self.p3_verticalLayout.setObjectName("p3_verticalLayout")
        self.gridLayout_6.addWidget(self.p3_widget, 0, 0, 1, 1)
        self.gridLayout_6.setColumnStretch(0, 1)
        self.gridLayout_6.setRowStretch(0, 2)
        self.gridLayout_6.setRowStretch(1, 1)
        self.stackedWidget.addWidget(self.page3)
        self.page4 = QtWidgets.QWidget()
        self.page4.setObjectName("page4")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.page4)
        self.gridLayout_13.setObjectName("gridLayout_13")
        spacerItem30 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_13.addItem(spacerItem30, 1, 1, 1, 1)
        spacerItem31 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_13.addItem(spacerItem31, 0, 1, 1, 1)
        self.p4_widget = QtWidgets.QWidget(self.page4)
        self.p4_widget.setStyleSheet("")
        self.p4_widget.setObjectName("p4_widget")
        self.p4_verticalLayout = QtWidgets.QVBoxLayout(self.p4_widget)
        self.p4_verticalLayout.setObjectName("p4_verticalLayout")
        self.gridLayout_13.addWidget(self.p4_widget, 0, 0, 1, 1)
        self.p4_groupBox = QtWidgets.QGroupBox(self.page4)
        self.p4_groupBox.setStyleSheet("QGroupBox{\n"
"                  padding-right: 15px;\n"
"                   border-style:inset;                  \n"
"                   border-width:5px;                    \n"
"                   border-radius:5px;                   \n"
"                   border-color:rgb(255,255,255);   \n"
"                   font:bold 18px;                       \n"
"                   color:rgba(255,255,255,255);                \n"
"                   padding:6px; \n"
"}")
        self.p4_groupBox.setAlignment(QtCore.Qt.AlignCenter)
        self.p4_groupBox.setObjectName("p4_groupBox")
        self.gridLayout_14 = QtWidgets.QGridLayout(self.p4_groupBox)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.p4_btn_saveResult = QtWidgets.QPushButton(self.p4_groupBox)
        self.p4_btn_saveResult.setStyleSheet("\n"
"QPushButton{\n"
" image-position: left;\n"
"\n"
"                  padding-right: 15px;\n"
"                   border-style:inset;                  \n"
"                   border-width:2px;                    \n"
"                   border-radius:1px;                   \n"
"                   border-color:rgba(255,255,255,100);   \n"
"                   font:18px;                       \n"
"                   color:rgb(2,2,2);                \n"
"                   padding:6px; \n"
"\n"
"}\n"
" QPushButton:hover{\n"
"                   background-color:rgb(200,225,255);\n"
"                   border-color:rgba(255,255,255,200);\n"
"                   color:rgba(0,0,0,200);\n"
"font:bold 20px;\n"
"                   }")
        self.p4_btn_saveResult.setIcon(icon5)
        self.p4_btn_saveResult.setObjectName("p4_btn_saveResult")
        self.gridLayout_14.addWidget(self.p4_btn_saveResult, 2, 1, 1, 1)
        spacerItem32 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_14.addItem(spacerItem32, 3, 1, 1, 1)
        spacerItem33 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_14.addItem(spacerItem33, 3, 0, 1, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(self.p4_groupBox)
        self.groupBox_3.setStyleSheet("QGroupBox{\n"
"                  padding-right: 15px;\n"
"                   border-style:inset;                  \n"
"                   border-width:1px;                    \n"
"                   border-radius:1px;                   \n"
"                   border-color:rgb(255,255,255);   \n"
"                   font: 18px;                       \n"
"                   color:rgb(2,2,2);                \n"
"                   padding:6px; \n"
"}\n"
"\n"
"QPushButton{\n"
" image-position: left;\n"
"\n"
"                  padding-right: 15px;\n"
"                   border-style:inset;                  \n"
"                   border-width:2px;                    \n"
"                   border-radius:1px;                   \n"
"                   border-color:rgba(255,255,255,100);   \n"
"                   font:18px;                       \n"
"                   color:rgb(2,2,2);                \n"
"                   padding:6px; \n"
"\n"
"}\n"
" QPushButton:hover{\n"
"                   background-color:rgb(200,225,255);\n"
"                   border-color:rgba(255,255,255,200);\n"
"                   color:rgba(0,0,0,200);\n"
"font:bold 20px;\n"
"                   }\n"
"QLabel{\n"
"font:16px;                       \n"
"color:rgb(2,2,2);                \n"
"}\n"
"QComboBox{\n"
"background-color: rgba(255, 255, 255,10);\n"
"border:1px solid rgba(228,228,228,100);\n"
"border-radius:5px 5px 0px 0px;\n"
"font-size:18px;\n"
"}\n"
"\n"
"\n"
"QComboBox QAbstractItemView {\n"
"    outline: 0px solid gray;   /* 选定项的虚框 */\n"
"    border: 1px solid raga(228,228,228,100);   /* 整个下拉窗体的边框 */\n"
"    color: blue;\n"
"    background-color: white;   /* 整个下拉窗体的背景色 */\n"
"    selection-background-color: lightblue;   /* 整个下拉窗体被选中项的背景色 */\n"
"}")
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_15 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.p4_btn_predict = QtWidgets.QPushButton(self.groupBox_3)
        self.p4_btn_predict.setStyleSheet("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/images/resources/预测.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.p4_btn_predict.setIcon(icon7)
        self.p4_btn_predict.setIconSize(QtCore.QSize(20, 20))
        self.p4_btn_predict.setObjectName("p4_btn_predict")
        self.gridLayout_15.addWidget(self.p4_btn_predict, 1, 0, 1, 1)
        self.p4_checkBox_showReal = QtWidgets.QCheckBox(self.groupBox_3)
        self.p4_checkBox_showReal.setStyleSheet("QCheckBox{\n"
"  color:#666666;\n"
"  font-size:18px;\n"
"  padding: 1px 15px 1px 3px;\n"
"} ")
        self.p4_checkBox_showReal.setChecked(True)
        self.p4_checkBox_showReal.setObjectName("p4_checkBox_showReal")
        self.gridLayout_15.addWidget(self.p4_checkBox_showReal, 1, 1, 1, 1)
        self.p4_cb_modelchoose = QtWidgets.QComboBox(self.groupBox_3)
        self.p4_cb_modelchoose.setStyleSheet("")
        self.p4_cb_modelchoose.setObjectName("p4_cb_modelchoose")
        self.p4_cb_modelchoose.addItem("")
        self.p4_cb_modelchoose.addItem("")
        self.p4_cb_modelchoose.addItem("")
        self.p4_cb_modelchoose.addItem("")
        self.p4_cb_modelchoose.addItem("")
        self.p4_cb_modelchoose.addItem("")
        self.gridLayout_15.addWidget(self.p4_cb_modelchoose, 0, 0, 1, 2)
        self.gridLayout_14.addWidget(self.groupBox_3, 1, 0, 2, 1)
        self.p4_result = QtWidgets.QTextEdit(self.p4_groupBox)
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.p4_result.setFont(font)
        self.p4_result.setStyleSheet("font:15px;                       \n"
"color:rgba(255,255,255,200);                ")
        self.p4_result.setTextInteractionFlags(QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.p4_result.setObjectName("p4_result")
        self.gridLayout_14.addWidget(self.p4_result, 0, 1, 2, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.p4_groupBox)
        self.groupBox_2.setStyleSheet("QGroupBox{\n"
"                  padding-right: 15px;\n"
"                   border-style:inset;                  \n"
"                   border-width:1px;                    \n"
"                   border-radius:5px;                   \n"
"                   border-color:rgb(255,255,255);   \n"
"                   font: 18px;                       \n"
"                   color:rgb(2,2,2);                \n"
"                   padding:6px; \n"
"}\n"
"QLabel{\n"
"font:18px;                       \n"
"color:rgb(2,2,2);                \n"
"}\n"
"\n"
"QSpinBox{\n"
"padding-right: 15px; /* make room for the arrows */\n"
"border:1px solid rgba(228,228,228,100);\n"
"border-radius:5px;       \n"
"  \n"
"background-color: rgba(255, 255, 255,10);\n"
"font:18px;      \n"
"color:rgb(2,2,2);\n"
"} \n"
"\n"
"QSpinBox::up-button {\n"
"border-image: url(:/images/resources/spinbox-up.png);\n"
"}\n"
"\n"
"QSpinBox::down-button {\n"
"border-image: url(:/images/resources/spinbox-down.png);\n"
"}\n"
"\n"
"QSpinBox::up-button:pressed {\n"
"margin-top:3px;\n"
"}\n"
"\n"
"QSpinBox::down-button:pressed {\n"
"margin-bottom:3px;\n"
"}")
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_16 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.label_11 = QtWidgets.QLabel(self.groupBox_2)
        self.label_11.setObjectName("label_11")
        self.gridLayout_16.addWidget(self.label_11, 0, 1, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.groupBox_2)
        self.label_12.setObjectName("label_12")
        self.gridLayout_16.addWidget(self.label_12, 0, 3, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.groupBox_2)
        self.label_10.setObjectName("label_10")
        self.gridLayout_16.addWidget(self.label_10, 0, 8, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.groupBox_2)
        self.label_9.setObjectName("label_9")
        self.gridLayout_16.addWidget(self.label_9, 0, 6, 1, 1)
        self.p4_sb_year = QtWidgets.QSpinBox(self.groupBox_2)
        self.p4_sb_year.setMinimum(2004)
        self.p4_sb_year.setMaximum(2008)
        self.p4_sb_year.setSingleStep(1)
        self.p4_sb_year.setProperty("value", 2004)
        self.p4_sb_year.setObjectName("p4_sb_year")
        self.gridLayout_16.addWidget(self.p4_sb_year, 0, 2, 1, 1)
        self.p4_sb_month = QtWidgets.QSpinBox(self.groupBox_2)
        self.p4_sb_month.setMinimum(1)
        self.p4_sb_month.setMaximum(12)
        self.p4_sb_month.setObjectName("p4_sb_month")
        self.gridLayout_16.addWidget(self.p4_sb_month, 0, 4, 1, 1)
        self.p4_sb_zoneid = QtWidgets.QSpinBox(self.groupBox_2)
        self.p4_sb_zoneid.setMinimum(1)
        self.p4_sb_zoneid.setMaximum(21)
        self.p4_sb_zoneid.setObjectName("p4_sb_zoneid")
        self.gridLayout_16.addWidget(self.p4_sb_zoneid, 0, 0, 1, 1)
        self.p4_sb_day = QtWidgets.QSpinBox(self.groupBox_2)
        self.p4_sb_day.setMinimum(1)
        self.p4_sb_day.setMaximum(31)
        self.p4_sb_day.setProperty("value", 8)
        self.p4_sb_day.setObjectName("p4_sb_day")
        self.gridLayout_16.addWidget(self.p4_sb_day, 0, 7, 1, 1)
        self.gridLayout_14.addWidget(self.groupBox_2, 0, 0, 1, 1)
        self.gridLayout_14.setRowStretch(0, 1)
        self.gridLayout_14.setRowStretch(1, 1)
        self.gridLayout_14.setRowStretch(2, 1)
        self.gridLayout_13.addWidget(self.p4_groupBox, 1, 0, 1, 1)
        self.gridLayout_13.setColumnStretch(0, 1)
        self.gridLayout_13.setRowStretch(0, 2)
        self.gridLayout_13.setRowStretch(1, 1)
        self.stackedWidget.addWidget(self.page4)
        self.gridLayout_2.addWidget(self.stackedWidget, 0, 0, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_2, 0, 0, 2, 1)
        self.gridLayout_3.setColumnStretch(0, 4)
        self.gridLayout_3.setColumnStretch(1, 1)
        self.gridLayout_3.setRowStretch(0, 1)
        Mainwindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(Mainwindow)
        self.stackedWidget.setCurrentIndex(3)
        self.p3_sw_method.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Mainwindow)

    def retranslateUi(self, Mainwindow):
        _translate = QtCore.QCoreApplication.translate
        Mainwindow.setWindowTitle(_translate("Mainwindow", "电力负荷分析软件"))
        self.btn_1check.setText(_translate("Mainwindow", "数据查看"))
        self.btn_2show.setText(_translate("Mainwindow", "负荷监控"))
        self.btn_3clus.setText(_translate("Mainwindow", "负荷聚类"))
        self.btn_4fore.setText(_translate("Mainwindow", "负荷预测"))
        self.btn_help.setText(_translate("Mainwindow", "帮助    中心"))
        self.p0_textBrowser.setHtml(_translate("Mainwindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:36pt; font-weight:600; text-decoration: underline; color:#b8d5ff;\">电力负荷分析软件</span></p>\n"
"<p align=\"right\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16pt; color:#b8d5ff;\">柯思雄毕业设计作品</span></p>\n"
"<p align=\"right\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16pt; color:#b8d5ff;\">指导老师：方支剑</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16pt; color:#b8d4ff;\">本软件包含以下功能</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16pt; color:#b8d4ff;\">1、数据查看</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Arial\'; font-size:16pt; color:#b8d4ff;\">    •</span><span style=\" font-family:\'等线\'; font-size:16pt; color:#b8d4ff;\">负荷数据的增加；</span><span style=\" font-size:16pt; color:#b8d4ff;\"> </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Arial\'; font-size:16pt; color:#b8d4ff;\">    •</span><span style=\" font-family:\'等线\'; font-size:16pt; color:#b8d4ff;\">负荷数据的删除；</span><span style=\" font-size:16pt; color:#b8d4ff;\"> </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Arial\'; font-size:16pt; color:#b8d4ff;\">    •</span><span style=\" font-family:\'等线\'; font-size:16pt; color:#b8d4ff;\">负荷数据的修改；</span><span style=\" font-size:16pt; color:#b8d4ff;\"> </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Arial\'; font-size:16pt; color:#b8d4ff;\">    •</span><span style=\" font-family:\'等线\'; font-size:16pt; color:#b8d4ff;\">负荷数据的插叙；</span><span style=\" font-size:16pt; color:#b8d4ff;\"> </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'等线\'; font-size:16pt; color:#b8d4ff;\">    （按地区、日期查询、SQL查询、排序）</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16pt; color:#b8d4ff;\"> </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16pt; color:#b8d4ff;\">2、负荷监控</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Arial\'; font-size:16pt; color:#b8d4ff;\">    •</span><span style=\" font-family:\'等线\'; font-size:16pt; color:#b8d4ff;\">历史数据的按日负荷曲线可视化</span><span style=\" font-size:16pt; color:#b8d4ff;\"> </span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:16pt; color:#b8d4ff;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16pt; color:#b8d4ff;\">3、负荷聚类</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Arial\'; font-size:16pt; color:#b8d4ff;\">    •</span><span style=\" font-family:\'等线\'; font-size:16pt; color:#b8d4ff;\">数据选择</span><span style=\" font-size:16pt; color:#b8d4ff;\"> </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Arial\'; font-size:16pt; color:#b8d4ff;\">    •</span><span style=\" font-family:\'等线\'; font-size:16pt; color:#b8d4ff;\">聚类模型选择</span><span style=\" font-size:16pt; color:#b8d4ff;\"> </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Arial\'; font-size:16pt; color:#b8d4ff;\">    •</span><span style=\" font-family:\'等线\'; font-size:16pt; color:#b8d4ff;\">聚类分析结果显示</span><span style=\" font-size:16pt; color:#b8d4ff;\"> </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'等线\'; font-size:16pt; color:#b8d4ff;\">    （可视化曲线、数学解释）</span><span style=\" font-size:16pt; color:#b8d4ff;\"> </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Arial\'; font-size:16pt; color:#b8d4ff;\">    •</span><span style=\" font-family:\'等线\'; font-size:16pt; color:#b8d4ff;\">导出聚类分析结果为PDF</span><span style=\" font-size:16pt; color:#b8d4ff;\"> </span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:16pt; color:#b8d4ff;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16pt; color:#b8d4ff;\">4、负荷预测</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Arial\'; font-size:16pt; color:#b8d4ff;\">    •待</span><span style=\" font-family:\'等线\'; font-size:16pt; color:#b8d4ff;\">预测日的选择</span><span style=\" font-size:16pt; color:#b8d4ff;\"> </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Arial\'; font-size:16pt; color:#b8d4ff;\">    •</span><span style=\" font-family:\'等线\'; font-size:16pt; color:#b8d4ff;\">预测模型选择</span><span style=\" font-size:16pt; color:#b8d4ff;\"> </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Arial\'; font-size:16pt; color:#b8d4ff;\">    •</span><span style=\" font-family:\'等线\'; font-size:16pt; color:#b8d4ff;\">预测结果显示</span><span style=\" font-size:16pt; color:#b8d4ff;\"> </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'等线\'; font-size:16pt; color:#b8d4ff;\">    （可视化曲线、预测误差）</span><span style=\" font-size:16pt; color:#b8d4ff;\"> </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Arial\'; font-size:16pt; color:#b8d4ff;\">    •</span><span style=\" font-family:\'等线\'; font-size:16pt; color:#b8d4ff;\">导出预测结果为PDF</span><span style=\" font-size:16pt; color:#b8d4ff;\"> </span></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:16pt; color:#b8d4ff;\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt; color:#b8d4ff;\">如有问题 请联系作者：柯思雄（kktenega@gmail.com）</span></p></body></html>"))
        self.p1_groupBox.setTitle(_translate("Mainwindow", "数据查看"))
        self.groupBox_10.setTitle(_translate("Mainwindow", "排序方式"))
        self.p1_cb_paixu.setItemText(0, _translate("Mainwindow", "默认排序"))
        self.p1_cb_paixu.setItemText(1, _translate("Mainwindow", "以地区排序"))
        self.p1_cb_paixu.setItemText(2, _translate("Mainwindow", "以日期排序"))
        self.p1_cb_paixu.setItemText(3, _translate("Mainwindow", "以负荷排序"))
        self.p1_rb_paixu_zheng.setText(_translate("Mainwindow", "正序"))
        self.p1_rb_paixu_fan.setText(_translate("Mainwindow", "逆序"))
        self.label_8.setText(_translate("Mainwindow", "提示：SQL查询格式如：select * from where (zone_id = 0 and year = 2004 and h1>2000)"))
        self.groupBox_6.setTitle(_translate("Mainwindow", "日期查询"))
        self.label_0.setText(_translate("Mainwindow", "地区"))
        self.label_1.setText(_translate("Mainwindow", "年"))
        self.label_2.setText(_translate("Mainwindow", "月"))
        self.label_3.setText(_translate("Mainwindow", "日"))
        self.groupBox_9.setTitle(_translate("Mainwindow", "数据库SQL查询"))
        self.p1_lineEdit_sql.setPlaceholderText(_translate("Mainwindow", "zone_id = 0 and year =2004 and h1>2000"))
        self.p1_pushButton_search.setText(_translate("Mainwindow", "查询"))
        self.groupBox_8.setTitle(_translate("Mainwindow", "数据操作"))
        self.p1_btn_add.setText(_translate("Mainwindow", "增加"))
        self.p1_btn_save.setText(_translate("Mainwindow", "保存"))
        self.p1_btn_del.setText(_translate("Mainwindow", "删除"))
        self.p2_groupBox.setTitle(_translate("Mainwindow", "负荷监控"))
        self.p2_groupBox_zoonid.setTitle(_translate("Mainwindow", "区域"))
        self.p2_cb_6.setText(_translate("Mainwindow", "6"))
        self.p2_cb_14.setText(_translate("Mainwindow", "14"))
        self.p2_cb_17.setText(_translate("Mainwindow", "17"))
        self.p2_cb_5.setText(_translate("Mainwindow", "5"))
        self.p2_cb_15.setText(_translate("Mainwindow", "15"))
        self.p2_cb_20.setText(_translate("Mainwindow", "20"))
        self.p2_cb_13.setText(_translate("Mainwindow", "13"))
        self.p2_cb_4.setText(_translate("Mainwindow", "4"))
        self.p2_cb_19.setText(_translate("Mainwindow", "19"))
        self.p2_cb_18.setText(_translate("Mainwindow", "18"))
        self.p2_cb_1.setText(_translate("Mainwindow", "1"))
        self.p2_cb_11.setText(_translate("Mainwindow", "11"))
        self.p2_cb_2.setText(_translate("Mainwindow", "2"))
        self.p2_cb_16.setText(_translate("Mainwindow", "16"))
        self.p2_cb_8.setText(_translate("Mainwindow", "8"))
        self.p2_cb_12.setText(_translate("Mainwindow", "12"))
        self.p2_cb_9.setText(_translate("Mainwindow", "9"))
        self.p2_cb_10.setText(_translate("Mainwindow", "10"))
        self.p2_cb_3.setText(_translate("Mainwindow", "3"))
        self.p2_cb_7.setText(_translate("Mainwindow", "7"))
        self.groupBox_7.setTitle(_translate("Mainwindow", "查询日期"))
        self.label_4.setText(_translate("Mainwindow", "年"))
        self.label_5.setText(_translate("Mainwindow", "月"))
        self.label_6.setText(_translate("Mainwindow", "日"))
        self.groupBox_11.setTitle(_translate("Mainwindow", "功能选项"))
        self.p2_checkBox_data.setText(_translate("Mainwindow", "是否显示数据"))
        self.p2_checkBox_dhua.setText(_translate("Mainwindow", "有无动画"))
        self.p3_groupBox.setTitle(_translate("Mainwindow", "负荷聚类"))
        self.p3_btn_saveResult.setText(_translate("Mainwindow", "导出报告"))
        self.groupBox_4.setTitle(_translate("Mainwindow", "数据选择"))
        self.p3_btn1_choose.setText(_translate("Mainwindow", "请选择"))
        self.p3_listWidget.setSortingEnabled(False)
        self.groupBox_12.setTitle(_translate("Mainwindow", "功能选项"))
        self.p3_checkBox_showAve.setText(_translate("Mainwindow", "显示平均曲线"))
        self.groupBox_5.setTitle(_translate("Mainwindow", "聚类方法选择"))
        self.label_13.setText(_translate("Mainwindow", "......"))
        self.p3_label_cnum.setText(_translate("Mainwindow", "聚类数"))
        self.p3_label_eps.setText(_translate("Mainwindow", "eps"))
        self.p3_label_minpts.setText(_translate("Mainwindow", "minpts"))
        self.p3_cb_method.setItemText(0, _translate("Mainwindow", "请选择"))
        self.p3_cb_method.setItemText(1, _translate("Mainwindow", "K-均值"))
        self.p3_cb_method.setItemText(2, _translate("Mainwindow", "层次聚类"))
        self.p3_cb_method.setItemText(3, _translate("Mainwindow", "高斯模型"))
        self.p3_cb_method.setItemText(4, _translate("Mainwindow", "谱聚类"))
        self.p3_cb_method.setItemText(5, _translate("Mainwindow", "DBSCAN"))
        self.p4_groupBox.setTitle(_translate("Mainwindow", "负荷预测"))
        self.p4_btn_saveResult.setText(_translate("Mainwindow", "导出报告"))
        self.groupBox_3.setTitle(_translate("Mainwindow", "模型选择"))
        self.p4_btn_predict.setText(_translate("Mainwindow", "预测"))
        self.p4_checkBox_showReal.setText(_translate("Mainwindow", "显示真实值"))
        self.p4_cb_modelchoose.setItemText(0, _translate("Mainwindow", "请选择"))
        self.p4_cb_modelchoose.setItemText(1, _translate("Mainwindow", "ANN"))
        self.p4_cb_modelchoose.setItemText(2, _translate("Mainwindow", "LSTM"))
        self.p4_cb_modelchoose.setItemText(3, _translate("Mainwindow", "GRU"))
        self.p4_cb_modelchoose.setItemText(4, _translate("Mainwindow", "Kmeans-ANN"))
        self.p4_cb_modelchoose.setItemText(5, _translate("Mainwindow", "Kmeans-TCN-GRU"))
        self.groupBox_2.setTitle(_translate("Mainwindow", "预测日选择"))
        self.label_11.setText(_translate("Mainwindow", "地区"))
        self.label_12.setText(_translate("Mainwindow", "年"))
        self.label_10.setText(_translate("Mainwindow", "日"))
        self.label_9.setText(_translate("Mainwindow", "月"))
import res_rc
